### ISSUE TITLE
Create the String file 

### ISSUE THREAD

**Issue by Suryansh1720001** [NehaVns/Weather-Forecasting#41]
Creating the string file where all the strings are present

**Comment by Bayyana-kiran** [comment]
Can u assign me under iwoc?

**Comment by NehaVns** [comment]
@Bayyana-kiran 
I will assign it to you - if @Suryansh1720001 doesn't able to do it.
Because this issue is created by him. Until you can find more bugs in the application or try to enhance it by adding more issues in the project.
